name: build
on: [push]
env:
  CRYPTOGRAPHY_ALLOW_OPENSSL_102: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cd ansible && ansible-playbook build.yml